version: 1.3.{build}

environment:
  matrix:
  - python: 35
  - python: 35-x64
  - python: 36
  - python: 36-x64

install:
    - SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%
    - python -m pip.__main__ install -U pip wheel setuptools
    - pip install -r requirements.txt

build: off
build_script:
   # configure version
    - ps: >-
        If ($env:APPVEYOR_REPO_TAG -Eq "true" ) {
            $version = "$env:APPVEYOR_REPO_TAG_NAME"
        } Else {
            $version = "$env:APPVEYOR_BUILD_VERSION.dev0"
        }
        $version | Set-Content version.txt
    - python setup.py build bdist_wheel
    - ps: Get-ChildItem dist\*.whl | % { pip install $_.FullName }

test: off
test_script:
    - pip list
    - py.test -v tests
    - ps: Get-ChildItem dist\*.whl | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
